# Generated by Django 2.1 on 2019-10-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191016_0654'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
