# Generated by Django 2.1 on 2019-10-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191017_0201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
