# Generated by Django 2.1 on 2019-10-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191017_0208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
